/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2022-11-28 07:13:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_005fok_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");

    request.setCharacterEncoding("UTF-8"); 
    
    
      out.write("\r\n");
      out.write("    ");
      com.koreait.Member member = null;
      member = (com.koreait.Member) _jspx_page_context.getAttribute("member", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (member == null){
        member = new com.koreait.Member();
        _jspx_page_context.setAttribute("member", member, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("member"), request);
      out.write("\r\n");
      out.write("    ");
      com.koreait.MemberDAO dao = null;
      dao = (com.koreait.MemberDAO) _jspx_page_context.getAttribute("dao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (dao == null){
        dao = new com.koreait.MemberDAO();
        _jspx_page_context.setAttribute("dao", dao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입 완료</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	if(dao.join(member)){


      out.write("\r\n");
      out.write("	<h2>회원가입 완료</h2>\r\n");
      out.write("		<p>번호:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.koreait.Member)_jspx_page_context.findAttribute("member")).getIdx())));
      out.write("</p>\r\n");
      out.write("		<p>아이디: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.koreait.Member)_jspx_page_context.findAttribute("member")).getUserid())));
      out.write("</p>\r\n");
      out.write("		<p>비밀번호: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.koreait.Member)_jspx_page_context.findAttribute("member")).getUserpw())));
      out.write("</p>\r\n");
      out.write("		<p>이름: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.koreait.Member)_jspx_page_context.findAttribute("member")).getName())));
      out.write("</p>\r\n");
      out.write("		<p>이메일: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.koreait.Member)_jspx_page_context.findAttribute("member")).getEmail())));
      out.write("</p>\r\n");
      out.write("		<p>휴대폰번호: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.koreait.Member)_jspx_page_context.findAttribute("member")).getHp())));
      out.write("</p>\r\n");
      out.write("		<p>성별:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.koreait.Member)_jspx_page_context.findAttribute("member")).getGender())));
      out.write("</p>\r\n");
      out.write("        <p>취미:\r\n");
      out.write("        		");

				String hobbystr= "";
			for(String hobby : member.getHobby()){
				hobbystr = hobbystr + hobby + " ";
			}
			
			
      out.write("\r\n");
      out.write("			");
      out.print(hobbystr  );
      out.write("</p>\r\n");
      out.write("        <p>주민번호: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.koreait.Member)_jspx_page_context.findAttribute("member")).getSsn1())));
      out.write(' ');
      out.write('-');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.koreait.Member)_jspx_page_context.findAttribute("member")).getSsn2())));
      out.write("</p>\r\n");
      out.write("        <p>우편번호: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.koreait.Member)_jspx_page_context.findAttribute("member")).getZipcode())));
      out.write(" </p>\r\n");
      out.write("        <p>주소: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.koreait.Member)_jspx_page_context.findAttribute("member")).getAddress1())));
      out.write("</p>\r\n");
      out.write("        <p>상세주소: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.koreait.Member)_jspx_page_context.findAttribute("member")).getAddress2())));
      out.write("</p>\r\n");
      out.write("        <p>참고항목: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.koreait.Member)_jspx_page_context.findAttribute("member")).getAddress3())));
      out.write("</p>\r\n");
      out.write("        <p><a href=\"login.jsp\">로그인</a></p>\r\n");
      out.write("        ");

	}else{
        
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <h2>회원가입 실패!</h2>\r\n");
      out.write("	");

        }
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
