/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2022-12-02 05:31:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script defer src=\"./js/regist.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h2>회원가입</h2>\r\n");
      out.write("	<form action=\"./member_ok.jsp\" name=\"regform\" id=\"regform\"\r\n");
      out.write("		method=\"post\" onsubmit=\"return sendit()\">\r\n");
      out.write("		<input type =\"hidden\" name = \"isIdCheck\" id = \"isIdCheck\" value =\"n\">\r\n");
      out.write("		\r\n");
      out.write("		<p>\r\n");
      out.write("			아이디 : <input type=\"text\" name=\"userid\" id=\"userid\" maxlength=\"20\" onkeydown =\"idModify()\">\r\n");
      out.write("			<input type=\"button\" id=\"btnIdCheck\" value=\"중복체크\"\r\n");
      out.write("				onclick=\"clickBtn()\">\r\n");
      out.write("		</p>\r\n");
      out.write("		<p id=\"checkmsg\"></p>\r\n");
      out.write("		<p>\r\n");
      out.write("			비밀번호 : <input type=\"password\" name=\"userpw\" id=\"userpw\"\r\n");
      out.write("				maxlength=\"20\">\r\n");
      out.write("		</p>\r\n");
      out.write("		<p>\r\n");
      out.write("			비밀번호 확인 : <input type=\"password\" name=\"userpw_re\" id=\"userpw_re\"\r\n");
      out.write("				maxlength=\"20\">\r\n");
      out.write("		</p>\r\n");
      out.write("		<p>\r\n");
      out.write("			이름 : <input type=\"text\" name=\"name\" id=\"name\">\r\n");
      out.write("		</p>\r\n");
      out.write("		<p>\r\n");
      out.write("			휴대폰 번호 : <input type=\"text\" name=\"hp\" id=\"hp\">\r\n");
      out.write("		</p>\r\n");
      out.write("		<p>\r\n");
      out.write("			이메일 : <input type=\"text\" name=\"email\" id=\"email\">\r\n");
      out.write("		</p>\r\n");
      out.write("		<p>\r\n");
      out.write("			성별 :<label> 남자 <input type=\"radio\" name=\"gender\" value=\"남자\"\r\n");
      out.write("				checked></label> <label> 여자 <input type=\"radio\"\r\n");
      out.write("				name=\"gender\" value=\"여자\"></label>\r\n");
      out.write("		</p>\r\n");
      out.write("		<p>\r\n");
      out.write("			취미 : <label>등산<input type=\"checkbox\" name=\"hobby\" value=\"등산\"></label>\r\n");
      out.write("			<label>게임<input type=\"checkbox\" name=\"hobby\" value=\"게임\"></label>\r\n");
      out.write("			<label>영화감상<input type=\"checkbox\" name=\"hobby\" value=\"영화감상\"></label>\r\n");
      out.write("			<label>드라이브<input type=\"checkbox\" name=\"hobby\" value=\"드라이브\"></label>\r\n");
      out.write("			<label>운동<input type=\"checkbox\" name=\"hobby\" value=\"운동\"></label>\r\n");
      out.write("		</p>\r\n");
      out.write("		<p>\r\n");
      out.write("			주민등록번호 : <input type=\"text\" name=\"ssn1\"> -<input type=\"text\"\r\n");
      out.write("				name=\"ssn2\">\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<p>\r\n");
      out.write("			우편번호: <input type=\"text\" name=\"zipcode\" maxlength=\"5\"\r\n");
      out.write("				id=\"sample6_postcode\">\r\n");
      out.write("			<button type=\"button\" onclick=\"sample6_execDaumPostcode()\">검색</button>\r\n");
      out.write("		</p>\r\n");
      out.write("		<p>\r\n");
      out.write("			주소 <input type=\"text\" name=address1 id=\"sample6_address\">\r\n");
      out.write("		</p>\r\n");
      out.write("		<p>\r\n");
      out.write("			상세주소 <input type=\"text\" name=\"address2\" id=\"sample6_detailAddress\">\r\n");
      out.write("		</p>\r\n");
      out.write("		<p>\r\n");
      out.write("			참고사항 <input type=\"text\" name=\"address3\" id = \"sample6_extraAddress\">\r\n");
      out.write("		</p>\r\n");
      out.write("		<p>\r\n");
      out.write("			<button>가입완료</button>\r\n");
      out.write("			<button type=\"reset\">다시작성</button>\r\n");
      out.write("		</p>\r\n");
      out.write("	</form>\r\n");
      out.write("	<p>이미 회원이신가요? <a href='login.jsp'>로그인</a></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
